### ISSUE TITLE
Issue during build

### ISSUE THREAD

**Issue by sepine** [DynamicCodeSearch/COSAL#1]
Hi, I wanted to build the project, but got the following issues:
[ERROR] Failed to execute goal on project code: Could not resolve dependencies for project edu.ncsu.codeseer:code:jar:1.0-SNAPSHOT: Could not find artifact edu.ncsu.codeseer:atcoder:jar:1.0-SNAPSHOT at specified path /workspaces/experiment/COSAL/code/jars/atcoder-1.0-SNAPSHOT-jar-with-dependencies.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

So, how can I obtain the dependency atcoder-1.0-SNAPSHOT-jar-with-dependencies.jar ?

**Comment by LFWOvO** [comment]
Hi, I wanted to build the project, but got the following issues:
[ERROR] Failed to execute goal on project code: Could not resolve dependencies for project edu.ncsu.codeseer:code:jar:1.0-SNAPSHOT: Could not find artifact edu.ncsu.codeseer:atcoder:jar:1.0-SNAPSHOT at specified path /workspaces/experiment/COSAL/code/jars/atcoder-1.0-SNAPSHOT-jar-with-dependencies.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

So, how can I obtain the dependency atcoder-1.0-SNAPSHOT-jar-with-dependencies.jar ?
